// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// grid_probs
NumericVector grid_probs(IntegerMatrix X, NumericVector q, double delta, int median_loc);
RcppExport SEXP JOUSBoost_grid_probs(SEXP XSEXP, SEXP qSEXP, SEXP deltaSEXP, SEXP median_locSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type median_loc(median_locSEXP);
    __result = Rcpp::wrap(grid_probs(X, q, delta, median_loc));
    return __result;
END_RCPP
}
