# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
grid_probs <- function(X, q, delta, median_loc) {
    .Call('JOUSBoost_grid_probs', PACKAGE = 'JOUSBoost', X, q, delta, median_loc)
}

